openapi: 3.0.3
info:
  title: PxApi
  version: '1.0'
  description: "This api is part of the PX-family.\r\n Q: Should the tables and the navigate endpoint have different backends(Lucene vs sql)?"
paths:
  /topictree:
    get:
      tags:
        - TopicTree
      summary: "This has an include part, in stead of nested elements. \r\n The topictree starts here. Gets the treenode at the root node"
      operationId: GetTopics
      parameters:
        - $ref: '#/components/parameters/levelsParam'
        - $ref: '#/components/parameters/langParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseTreeNode'
              examples:
                oneLevel:
                  $ref: '#/components/examples/topictree-oneLevel'
                # twoLevels:
              #   $ref: '#/components/examples    topictree-twoLevels'
                threeLevels:
                  $ref: '#/components/examples/topictree-threeLevels'
                includedThreeLevels:
                  $ref: '#/components/examples/included-topictree-threeLevels'
        '429':
          $ref: '#/components/responses/ErrorResponse429'
  /topictree/{id}:
    get:
      tags:
        - TopicTree
      summary: Gets the TreeNode for the folder with the given id. (What should ids that are not folders return? )
      operationId: GetTopicsById
      parameters:
        - $ref: '#/components/parameters/levelsParam'
        - $ref: '#/components/parameters/treenodeIdParam'
        - $ref: '#/components/parameters/langParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseTreeNode'
              examples:
                # topictree_al:
                #   $ref: '#/components/examples/topictree_al-oneLevel'
                topictree_al_al03-oneLevel:
                  $ref: '#/components/examples/topictree_al_al03-oneLevel'
                topictree_al_al03_aku-oneLevel:
                  $ref: '#/components/examples/topictree_al_al03_aku-oneLevel'
components:
  parameters:
    langParam:
      name: lang
      in: query
      description: The language if the default is not what you want.
      required: false
      schema:
        type: string
      examples:
        X1:
          value: en
          summary: For english
        X2:
          value: dk
          summary: For danish
    treenodeIdParam:
      name: id
      in: path
      description: The TreeNode-id of the desired node
      required: true
      schema:
        type: string
    levelsParam:
      name: levels
      in: query
      description: Number of levels that are fetched in the response. Minimun 0, which will fetch all levels in the topictree.
      schema:
        type: integer
        format: int32
        default: 1
        minimum: 0
  schemas:
    BaseResponse:
      type: object
      description: Common properties for all responses. Abstract class.
      properties:
        error:
          type: string
          description: Errors will come here
          nullable: true
        info:
          type: string
          description: Messages on planed maintainence willl come here.
          nullable: true
      example:
        error: The id cant be found
        info: Closed on mondays
    ResponseTreeNode:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/ITreeNode'
      description: This holds information about the topictree of the api.
    Link:
      type: object
      properties:
        rel:
          type: string
          nullable: true
        href:
          type: string
          nullable: true
      additionalProperties: false
    Problem:
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the problem type.  When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          default: about:blank
          example: https://zalando.github.io/problem/constraint-violation
        title:
          type: string
          description: |
            A short, summary of the problem type. Written in english and readable
            for engineers (usually not suited for non technical stakeholders and
            not localized); example: Service Unavailable
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence
            of the problem.
          minimum: 100
          maximum: 600
          exclusiveMaximum: true
          example: 503
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the
            problem.
          example: Connection to database timed out
        instance:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
    ITreeNode:
      type: object
      description: Something that is one of 3 TreeNode types.
      discriminator:
         propertyName:  treeNodeType
         mapping:
           table: '#/components/schemas/TableTreeNode'
           heading: '#/components/schemas/HeadingTreeNode'
           folder: '#/components/schemas/FolderTreeNode'
      anyOf:
        - $ref: '#/components/schemas/TableTreeNode'
        - $ref: '#/components/schemas/HeadingTreeNode'
        - $ref: '#/components/schemas/FolderTreeNode'
    BaseTreeNode:
      type: object
      description: Common properties for the 3 TreeNode types.
      properties:
        id:
          type: string
          nullable: true
        treeNodeType:
          type: string
          nullable: true
          description: One of heading, table or folder
        label:
          type: string
          nullable: true
          description: Display text
        description:
          type: string
          nullable: true
          description: Longer text describing node.
        sortOrder:
          type: string
          description: Sort order.
    TableTreeNode:
      allOf:
        - $ref: '#/components/schemas/BaseTreeNode'
        - type: object
          description: Table treeNode
          properties:
            updated:
              type: string
              description: For treeNodeType "table"
              format: date-time
              nullable: true
            tags:
              type: array
              items:
                type: string
                description: tag for treenode
              nullable: true
            category:
              type: string
              description: Mostly for internal use. Which category table belongs to. internal, official, private or section. I, O, P, S
              default: official
              enum:
              - internal
              - official
              - private
              - section     
            links:
              type: array
              items:
                $ref: '#/components/schemas/Link'
              description: Not for Heading
              nullable: true
    FolderTreeNode:
      allOf:
        - $ref: '#/components/schemas/BaseTreeNode'
        - type: object
          description: Folder node
          properties:
            tags:
              type: array
              items:
                type: string
                description: tag for TreeNode
              nullable: true
            folderContent:
              type: array
              items:
                $ref: '#/components/schemas/ITreeNode'
              nullable: true
            included:
              type: array
              items:
                $ref: '#/components/schemas/ITreeNode'
              nullable: true
              description: Holds the included (prefetched) nodes.
            links:
              type: array
              items:
                $ref: '#/components/schemas/Link'
              description: Not for Heading
              nullable: true
    HeadingTreeNode:
      allOf:
        - $ref: '#/components/schemas/BaseTreeNode'
        - type: object
          description: Pedaled Vehicle
          properties:
             maxSpeed:
               description: The top speed in kilometers per hour rounded to the nearest integer.
               type: integer
               example: 83         
  responses:
    ErrorResponse429:
      description: Error respsone for 429
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
          example:
            title: Too many requests
            status: 429
            detail: You have reach the threshold for request limiting. 30 request per minute.
  examples:
    nestedContent:
      value:
        data:
          id: 'NESTED'
          treeNodeType: folder
          label: null
          sortOrder: 42
          links: null
          folderContent:
            - id: al
              treeNodeType: folder
              label: Folder 1
              sortOrder: 43
              links:
                - rel: data?
                  href: '#/included/al'
            - id: AKUAarNY
              treeNodeType: table
              label: '05111: Table in root folder'
              sortOrder: 44
              links:
                - rel: tables
                  href: https://my-site.com/api/v2/tables/AKUAarNY
          included:
            - id: al
              treeNodeType: folder
              label: Folder 1
              sortOrder: 43
              links: null
              folderContent:
                - id: al_al03
                  treeNodeType: closed-folder
                  label: Folder 1 1
                  sortOrder: 45
                  links:
                    - rel: data
                      href: https://localhost:7067/navigate/treealt2/al_al03
                - id: ForstgenArbNye
                  treeNodeType: table
                  label: '07116: Table in Folder 1'
                  sortOrder: 46
                  links:
                    - rel: metadata
                      href: https://my-site.com/api/v2/tables/ForstgenArbNye
                - id: al_al04
                  treeNodeType: closed-folder
                  label: Folder 1 2
                  sortOrder: 47
                  links:
                    - rel: data
                      href: https://localhost:7067/navigate/treealt2/al_al04
    included-topictree-threeLevels:
      description: This is an example of included content for three levels
      value:
        data:
          id: 
          treeNodeType: folder
          label: 
          links: 
          folderContent:
            - id: al
              treeNodeType: folder
              label: Arbeid og lønn
              tags: 
                - arbeid
                - lønn
                - jobb
                - inntekt
              links:
                - rel: data?
                  href: '#/included/al'
            - id: bf
              treeNodeType: folder
              label: Bank og finansmarked
              links:
                - rel: data?
                  href: '#/included/bf'
          included:
            - id: al
              treeNodeType: folder
              label: Arbeid og lønn
              links:
              folderContent:
                - id: al_al03
                  treeNodeType: folder
                  label: Arbeidsledighet
                  links:
                    - rel: data?
                      href: '#/included/al_al03'
                - id: al_al04
                  treeNodeType: folder
                  label: Arbeidsmiljø, sykefravær og arbeidskonflikter
                  description: Streiker, sykefravær og hvordan vi har det på jobb
                  links:
                    - rel: data?
                      href: '#/included/al_al04'
            - id: al_al03
              treeNodeType: folder
              label: Arbeidsledighet
              description: Inkluderer tall om ledige stillinger
              links:
              folderContent:
                - id: al_al03_aku
                  treeNodeType: folder
                  label: Arbeidskraftundersøkelsen
                  description: 
                  links:
                    - rel: data?
                      href: /api/topictree/al_al03_aku
                - id: al_al03_innvarbl
                  treeNodeType: folder
                  label: Registrerte arbeidsledige blant innvandrere (avsluttet i Statistisk sentralbyrå)
                  description: 
                  links:
                    - rel: data?
                      href: /api/topictree/al_al03_innvarbl
            - id: al_al04
              treeNodeType: folder
              label: Arbeidsmiljø, sykefravær og arbeidskonflikter
              description: Streiker, sykefravær og hvordan vi har det på jobb
              links: 
              folderContent:
                - id: al_al04_arbmiljo
                  treeNodeType: folder
                  label: Arbeidsmiljø, levekårsundersøkelsen
                  description: 
                  links:
                    - rel: data?
                      href: /api/topictree/al_al04_arbmiljo
                - id: al_al04_arborg
                  treeNodeType: folder
                  label: Fagforeiningsmedlemmer og streikar
                  description: 
                  links:
                    - rel: data?
                      href: /api/topictree/al_al04_arborg
            - id: bf
              treeNodeType: folder
              label: Bankk og finansmarked
              description: 
              links: 
              folderContent:
                - id: bf_bf02
                  treeNodeType: folder
                  label: Finansielle indikatorer
                  description: 
                  links:
                    - rel: data?
                      href: '#/included/bf_bf02'
            - id: bf_bf02
              treeNodeType: folder
              label: Finansielle indikatorer
              description: Nøkkeltall for finanssektoren
              links:
              folderContent:
                - id: bf_bf02_finsek
                  treeNodeType: folder
                  label: Finansielle sektorregnskaper
                  description: 
                  links:
                    - rel: data?
                      href: /api/topictree/bf_bf02_finsek
                - id: bf_bf02_konkurs
                  treeNodeType: folder
                  label: Opna konkursar
                  description: 
                  links:
                    - rel: data?
                      href: /api/topictree/ bf_bf02_konkurs


    topictree-oneLevel:
      description: Example for response with query paramter 'Levels' = 1
      value:
        data:
          id: 
          treeNodeType: folder
          label: 
          description:
          links: 
          folderContent:
            - id: al
              treeNodeType: folder
              label: Arbeid og lønn
              tags: 
                - arbeid
                - lønn
                - jobb
                - inntekt
              description: 
              links:
                - rel: data?
                  href: /api/topictree/al
            - id: bf
              treeNodeType: folder
              label: Bankk og finansmarked
              description: 
              links:
                - rel: data?
                  href: /api/topictree/bf
    topictree-twoLevels:
      description: Example for response with query paramter `Levels` = 2
      value:
        data:
          id: 
          treeNodeType: folder
          label: 
          description: 
          folderContent:
            - id: al
              treeNodeType: folder
              label: Arbeid og lønn
              description: 
              links:
              folderContent:
                - id: al_al03
                  treeNodeType: folder
                  label: Arbeidsledighet
                  description: Inkluderer tall om ledige stillinger
                  links:
                    - rel: data?
                      href: /api/topictree/al_al03
                - id: al_al04
                  treeNodeType: folder
                  label: Arbeidsmiljø, sykefravær og arbeidskonflikter
                  description: Streiker, sykefravær og hvordan vi har det på jobb
                  links:
                    - rel: data?
                      href: /api/topictree/al_al04
            - id: bf
              treeNodeType: folder
              label: Bankk og finansmarked
              description: 
              links: null
              folderContent:
                - id: bf_bf02
                  treeNodeType: folder
                  label: Finansielle indikatorer
                  description: 
                  links:
                    - rel: data?
                      href: /api/topictree/bf_bf02
    topictree-threeLevels:
      description: Example for response with query paramter 'Levels' = 3
      value:
        data:
          id: 
          treeNodeType: folder
          label: 
          description: 
          folderContent:
            - id: al
              treeNodeType: folder
              label: Arbeid og lønn
              tags: 
                - arbeid
                - lønn
                - jobb
                - inntekt
              description: 
              links: 
              folderContent:
                - id: al_al03
                  treeNodeType: folder
                  label: Arbeidsledighet
                  description: Inkluderer tall om ledige stillinger
                  links: 
                  folderContent:
                    - id: al_al03_aku
                      treeNodeType: folder
                      label: Arbeidskraftundersøkelsen
                      description: 
                      links:
                        - rel: data?
                          href: /api/topictree/al_al03_aku
                    - id: al_al03_innvarbl
                      treeNodeType: folder
                      label: Registrerte arbeidsledige blant innvandrere (avsluttet i Statistisk sentralbyrå)
                      description: 
                      links:
                        - rel: data?
                          href: /api/topictree/al_al03_innvarbl
                - id: al_al04
                  treeNodeType: folder
                  label: Arbeidsmiljø, sykefravær og arbeidskonflikter
                  description: Streiker, sykefravær og hvordan vi har det på jobb
                  links: 
                  folderContent:
                    - id: al_al04_arbmiljo
                      treeNodeType: folder
                      label: Arbeidsmiljø, levekårsundersøkelsen
                      description: 
                      links:
                        - rel: data?
                          href: /api/topictree/al_al04_arbmiljo
                    - id: al_al04_arborg
                      treeNodeType: folder
                      label: Fagforeiningsmedlemmer og streikar
                      description: 
                      links:
                        - rel: data?
                          href: /api/topictree/al_al04_arborg
            - id: bf
              treeNodeType: folder
              label: Bankk og finansmarked
              description: 
              links: null
              folderContent:
                - id: bf_bf02
                  treeNodeType: folder
                  label: Finansielle indikatorer
                  description: Nøkkeltall for finanssektoren
                  links: null
                  folderContent:
                    - id: bf_bf02_finsek
                      treeNodeType: folder
                      label: Finansielle sektorregnskaper
                      description: 
                      links:
                        - rel: data?
                          href: /api/topictree/bf_bf02_finsek
                    - id: bf_bf02_konkurs
                      treeNodeType: folder
                      label: Opna konkursar
                      description: 
                      links:
                        - rel: data?
                          href: /api/topictree/ bf_bf02_konkurs
    topictree_al-oneLevel:
      description: Example response for endpoint `topictree/{al}`
      value:
        data:
          id: al
          treeNodeType: folder
          label: Arbeid og lønn
          description: 
          links: null
          folderContent:
            - id: al_al03
              treeNodeType: folder
              label: Arbeidsledighet
              description: Inkluderer tall om ledige stillinger
              links:
                - rel: data?
                  href: /api/topictree/al_al03
            - id: al_al04
              treeNodeType: folder
              label: Arbeidsmiljø, sykefravær og arbeidskonflikter
              description: Streiker, sykefravær og hvordan vi har det på jobb 
              links:
                - rel: data?
                  href: /api/topictree/al_al04
    topictree_al_al03-oneLevel:
      description: Example response for endpoint `topictree/{al_al03}`
      value:
        data:
          id: al_al03
          treeNodeType: folder
          label: Arbeidsledighet
          description: Inkluderer tall om ledige stillinger
          links: null
          folderContent:
            - id: al_al03_aku
              treeNodeType: folder
              label: Arbeidskraftundersøkelsen
              description: 
              links:
                - rel: data?
                  href: /api/topictree/al_al03_aku
            - id: al_al03_innvarbl
              treeNodeType: folder
              label: Registrerte arbeidsledige blant innvandrere (avsluttet i Statistisk sentralbyrå)
              description: 
              links:
                - rel: data?
                  href: /api/topictree/al_al03_innvarbl
    topictree_al_al03_aku-oneLevel:
      description: Example response for endpoint `topictree/{al_al03_aku}`
      value:
        data:
          id: al_al03_aku
          treeNodeType: folder
          label: Arbeidskraftundersøkelsen
          description: 
          links: null
          folderContent:
            - id: al_al03_aku_SBMENU9729
              treeNodeType: heading
              label: Bruddjusterte tall
              description: 
              links:
                - rel: data?
                  href: /api/topictree/al_al03_aku_SBMENU9729
            - id: al_al03_aku_SyssArbledSes03
              treeNodeType: table
              label: "13332: Sysselsetting, arbeidsledighet, arbeidsstyrken og utførte ukeverk, etter kjønn og alder. Brudd- og sesongjustert, 3-måneders glidende gjennomsnitt 2006M02 - 2022M01"
              description: 
              links:
                - rel: data?
                  href: /api/topictree/al_al03_aku_SyssArbledSes03
tags:
  - name: TopicTree
    description: Endpoints for the topictree.